version: '3.8'

services:
  postgres:
    image: postgres:17.4-alpine
    container_name: postgres-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_DB: 'sensora'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'ruth'
    ports:
      - "5452:5432"
    volumes:
      - ./database_scripts:/docker-entrypoint-initdb.d/
    restart: unless-stopped

volumes:
  pgdata: